### ISSUE TITLE
Request to remove unauthorized reupload

### ISSUE THREAD

**Issue by StarCrusher96** [KochieBR/GalaxiesUnbound-Reupload#1]
Hi!

I recently noticed that you have reuploaded my mod to GitHub under the title "Galaxies Unbound-Reupload." While I appreciate your interest and effort to provide proper attribution, I need to clarify that this reupload was done without my permission and is in violation of the mod's license terms.

The "Galaxies Unbound" mod is licensed under the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0) license. This license allows for sharing with proper attribution but explicitly prohibits redistribution without the original creator's permission, especially when the mod is taken down for maintenance or updates.

Furthermore, this reupload violates GitHub’s Terms of Service, which require users to respect the intellectual property rights of others. Unauthorized redistribution of my mod is against these terms.

As the original author, I am currently working on updates and improvements for the mod. Therefore, I kindly request that you remove the reupload from GitHub immediately. Failure to comply with this request may result in further action, including filing a DMCA takedown (in 2 hours this will be filed) notice with GitHub. This could lead to the repository being forcibly removed and potential penalties to your GitHub account.

If you have any questions or would like to discuss this further, please feel free to reach out to me. I believe we both want what is best for the KSP community, and I appreciate your understanding and cooperation in this matter.

Thank you for your prompt attention to this request.

Best regards, 
StarCrusher96

**Comment by StarCrusher96** [comment]
Dear Kochi,

Thank you for your prompt response. I appreciate your effort to comply with the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International (CC-BY-NC-ND 4.0) license. However, I need to clarify a few important points.

While the CC BY-NC-ND 4.0 license does allow for sharing with proper attribution, it also requires that any redistribution respects the original creator's rights, including the right to control where and how the work is distributed. The license does not grant unconditional rights to reupload without explicit permission from the original creator, especially if the content has been temporarily taken down for maintenance or updates.

Moreover, GitHub's [Terms of Service](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service) require users to respect the intellectual property rights of others. Unauthorized redistribution without explicit permission, even if attributed correctly, can still be considered a violation of these terms. Here is a direct excerpt from [GitHub’s Terms of Service](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#5-license-grant-to-other-users):

> "You may only use the content of other users to the extent permitted by the owner's license or as otherwise expressly permitted by GitHub."

Your reupload, though well-intentioned, was done without my explicit permission. As the original author, I am actively maintaining and updating the mod. To ensure that users receive the most up-to-date and accurate version, I must retain control over its distribution.

Therefore, I kindly request that you remove the reupload from both GitHub and SpaceDock immediately. Since this request has not been complied with thus far, I have already filed a DMCA takedown notice with both platforms. This could lead to the forced removal of the content and potential penalties to your accounts.

I appreciate your understanding and cooperation in this matter. Please let me know once the repositories have been taken down.

Best regards,
StarCrusher96

**Comment by KochieBR** [comment]
The CC-BY-NC-ND 4.0 license does not require authorization from the author since the moment the content is posted under this license, it is understood as authorization. I am respecting the original creator's rights by giving unilateral credit and offering to take down my reupload once the content is reuploaded under the original creator's name. Under the guidelines of the CC-BY-NC-ND 4.0 license, the author cannot waive these rights. I am doing this to preserve the content on the internet, as I am a strong advocate of this idea.

Additionally, under the GitHub TOS, the content can be reuploaded to the extent allowed by the owner's license, which in this case permits my actions. I agree that users deserve the most up-to-date and accurate version of the mod, which is why I am offering to take it down once it is updated and reuploaded.

Therefore, the DMCA takedown request is invalid as there are no violations of the CC-BY-NC-ND 4.0 license.

**Comment by StarCrusher96** [comment]
Dear Kochi,

This will be my final communication on this matter. I appreciate your dedication to preserving content, but I must emphasize the following critical points with clear references to the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International (CC-BY-NC-ND 4.0) license and GitHub Terms of Service.

1. **Authorization Requirement**: The [CC BY-NC-ND 4.0 license](https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode) allows sharing under strict conditions. The license states in Section 3(a):

   > "You may Distribute the Licensed Material only under the terms of this Public License. You must include the following, at a minimum, if it is not already included in the Licensed Material: (i) the identification of the creator(s) of the Licensed Material and any others designated to receive attribution, in any reasonable manner requested by the Licensor (including by pseudonym if designated); (ii) a copyright notice; (iii) a notice that refers to this Public License; (iv) a notice that refers to the disclaimer of warranties; (v) a URI or hyperlink to the Licensed Material to the extent reasonably practicable; (vi) the license URI or hyperlink; and (vii) to the extent reasonably practicable, the name of the Licensor."

   This means that while you can share the content with proper attribution, it does not give you unconditional rights to reupload the content without explicit permission from the original creator, particularly when the creator is actively managing the distribution of their work.

2. **NoDerivatives Clause**: Section 2(a)(3) of the license specifies:

   > "NoDerivatives — If You Share the Licensed Material (including in modified form), You may not remix, transform, or build upon the material, and You must not Distribute modified material."

   Although your reupload does not modify the content, this clause emphasizes that redistribution must respect the original creator's terms and intentions. As the original creator, I have taken down the content for updates, and unauthorized reupload disrupts this process.

3. **License Termination**: According to Section 6(a) of the CC BY-NC-ND 4.0 license:

   > "This Public License applies for the term of the Copyright and Similar Rights licensed here. However, if You fail to comply with this Public License, then Your rights under this Public License terminate automatically."

   Since you did not obtain explicit permission for reuploading, your rights under the license have automatically terminated.

4. **GitHub Terms of Service**: GitHub's [Terms of Service](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service) explicitly state in Section D:

   > "You may only use the content of other users to the extent permitted by the owner's license or as otherwise expressly permitted by GitHub."

   Unauthorized redistribution without the explicit permission of the original creator is a violation of GitHub’s Terms of Service, even if attribution is provided. The license allows sharing under certain conditions, but it does not grant the right to reupload content taken down by the original author.

5. **DMCA Takedown Validity**: The DMCA takedown request is valid because the reupload was done without my explicit permission, violating both the CC BY-NC-ND 4.0 license terms and GitHub’s Terms of Service. As the copyright holder, I have the right to enforce the terms of the license and request the removal of unauthorized content.

Failure to comply with this request will result in further legal action, including escalation to GitHub and SpaceDock support teams, and potential penalties to your accounts. This is non-negotiable.

Please confirm once the repositories have been taken down to avoid further actions.

Thank you for your understanding and cooperation.

Best regards,
StarCrusher96

**Comment by KochieBR** [comment]
I am sharing the content under the rights that the CC-BY-NC-ND 4.0 license allows me.

As stated The licensor grants the public permission to use the licensed material under specified terms and conditions. These conditions include redistributing the content "as it is" with no modifications, which is exactly how I am doing it. 
As the author, you do not have the right to restrict the form in which I am redistributing the work

You are free to:
Share — copy and redistribute the material in any medium or format. The licensor cannot revoke these freedoms as long as you follow the license terms.

[source:](https://creativecommons.org/licenses/by-nc-nd/4.0).

 If you wanted to have more control over the distribution, an appropriate license such as "All Rights Reserved" or "Some Rights Reserved" should have been used originally.

As stated above, I am reuploading the content as it is with no modifications other than an edit to the README file to clarify the state of the reupload and acknowledge the original author as required by the license.

Therefore, I am not violating the terms of the CC-BY-NC-ND 4.0 license or the intentions over licensing the content under a "Free" license such as this one . These rights cannot be waived.

GitHub states that the content of other users is allowed to the extent permitted by the owner's license (CC-BY-NC-ND 4.0), which I am following by giving unilateral credit, not utilizing it in any commercial form, and redistributing it as it is with no modifications.

As stated above, the license gives me the right to redistribute the content without further authorization. However, I affirm that you have the rights to enforce these terms if the license is violated.

I strongly recommend reviewing the license terms once more before engaging in any further legal action, as your points do not align with the original text of the license. 

I will be glad to explain this situation to SpaceDock and GitHub support teams and am aware of possible consequences.

This is my last message on this matter.

Best regards,
Kochi

**Comment by HebaruSan** [comment]
Hi, SpaceDock admin here. As far as I can tell, removing this download would violate @KochieBR's rights to share, copy and distribute granted by the CC-BY-NC-ND-4.0 license, so I won't be doing that. I have not yet heard from the other admins about this, but I'll be in touch with them to make sure they're fully informed.
