### ISSUE TITLE
Systems not included in the SpaceDock DL

### ISSUE THREAD

**Issue by koimeiji** [KochieBR/GalaxiesUnbound-Reupload#2]
Not sure if it's intentional, or was just an absentminded mistake, but the SpaceDock download doesn't actually include the systems itself, which (currently) need to be manually installed from here, the github.

**Comment by KochieBR** [comment]
Sorry for the late response, yes its intentionally the spacedock servers have some stability issues when uploading big files I will upload all of the extra systems on spacedock once it's stable
