### ISSUE TITLE
Primary Systems missing

### ISSUE THREAD

**Issue by BeFranke** [KochieBR/GalaxiesUnbound-Reupload#3]
As far as I can see, all the primary systems (as they are called in general settings, e.g. Alpha Centauri / Nova Kirbani) are not included in the repository, am I missing something?

Thank you for the re-upload!

**Comment by KochieBR** [comment]
Good Catch. It appears that I made a mistake and assumed the core file would include the primary systems. I managed to recover the files for them for the 1.2.5 version and, according to the change log, they should be compatible. I will be uploading them here and on spacedock.

Best Regards
Kochi

**Comment by BeFranke** [comment]
Thanks for your work, really appreciate it!
